In [16]:
from pathlib import Path

In [42]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [34]:
data_folder = Path(".")

employees_path = data_folder / "employees.csv"
departments_path = data_folder / "departments.csv"
payroll_path=data_folder / "payroll.csv"
attendance_path=data_folder/"attendance.csv"
performance_path=data_folder/"performance_reviews.csv"

In [17]:
employees = pd.read_csv(employees_path)

In [24]:
departments=pd.read_csv(departments_path)

In [25]:
payroll=pd.read_csv(payroll_path)

In [192]:
payroll.shape

(60000, 5)

In [26]:
performance=pd.read_csv(attendance_path)

In [193]:
performance=pd.read_csv(performance_path)

In [194]:
performance.shape

(10000, 4)

In [41]:
employees.shape

(10100, 9)

In [43]:
departments.shape

(20, 3)

In [44]:
payroll.shape

(60000, 5)

In [45]:
attendance.shape

(10000, 4)

In [46]:
performance.shape

(50000, 5)

In [48]:
employees.head()

,employee_id,employee_code,gender,age,department_id,job_title,join_date,salary,email
0,1,EMP00001,M,29.0,13.0,Intern,2023-01-15,350000,emp1@mail.com
1,2,EMP00002,M,57.0,2.0,QA,15/02/2024,350000,emp2@mail.com
2,3,EMP00003,F,46.0,3.0,Engineer,2023-01-15,-10000,NaN
3,4,EMP00004,Male,56.0,4.0,Engineer,NaN,350000,NaN
4,5,EMP00005,Male,34.0,2.0,QA,15/02/2024,800000,NaN

In [50]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    10100 non-null  int64
 1   employee_code  10100 non-null  object
 2   gender         8397 non-null   object
 3   age            9856 non-null   float64
 4   department_id  9666 non-null   float64
 5   job_title      10100 non-null  object
 6   join_date      6135 non-null   object
 7   salary         8444 non-null   object
 8   email          5093 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 710.3+ KB

In [53]:
employees.describe()

        employee_id          age  department_id
count  10100.000000  9856.000000    9666.000000
mean    4999.962277    40.421469      14.824643
std     2886.828406    16.141985      19.917548
min        1.000000    -2.000000       1.000000
25%     2498.750000    29.000000       6.000000
50%     4998.500000    40.000000      11.000000
75%     7501.250000    51.000000      16.000000
max    10000.000000    99.000000      99.000000

In [55]:
employees.isnull().sum()

employee_id         0
employee_code       0
gender           1703
age               244
department_id     434
job_title           0
join_date        3965
salary           1656
email            5007
dtype: int64

In [57]:
employees.duplicated().sum()

100

In [58]:
attendance.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   review_id    10000 non-null  int64
 1   employee_id  9999 non-null   float64
 2   rating       8763 non-null   float64
 3   remarks      8407 non-null   object
dtypes: float64(2), int64(1), object(1)
memory usage: 312.6+ KB

In [59]:
departments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   department_id    20 non-null     int64
 1   department_name  20 non-null     object
 2   location         20 non-null     object
dtypes: int64(1), object(2)
memory usage: 608.0+ bytes

In [60]:
employees.head()

,employee_id,employee_code,gender,age,department_id,job_title,join_date,salary,email
0,1,EMP00001,M,29.0,13.0,Intern,2023-01-15,350000,emp1@mail.com
1,2,EMP00002,M,57.0,2.0,QA,15/02/2024,350000,emp2@mail.com
2,3,EMP00003,F,46.0,3.0,Engineer,2023-01-15,-10000,NaN
3,4,EMP00004,Male,56.0,4.0,Engineer,NaN,350000,NaN
4,5,EMP00005,Male,34.0,2.0,QA,15/02/2024,800000,NaN

In [61]:
employees.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10100 entries, 0 to 10099
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   employee_id    10100 non-null  int64
 1   employee_code  10100 non-null  object
 2   gender         8397 non-null   object
 3   age            9856 non-null   float64
 4   department_id  9666 non-null   float64
 5   job_title      10100 non-null  object
 6   join_date      6135 non-null   object
 7   salary         8444 non-null   object
 8   email          5093 non-null   object
dtypes: float64(2), int64(1), object(6)
memory usage: 710.3+ KB

In [62]:
employees.isnull().sum()

employee_id         0
employee_code       0
gender           1703
age               244
department_id     434
job_title           0
join_date        3965
salary           1656
email            5007
dtype: int64

In [63]:
(employees=="").sum()

employee_id      0
employee_code    0
gender           0
age              0
department_id    0
job_title        0
join_date        0
salary           0
email            0
dtype: int64

In [65]:
(employees.apply(lambda x : x.astype(str).str.strip()=="")).sum()

employee_id      0
employee_code    0
gender           0
age              0
department_id    0
job_title        0
join_date        0
salary           0
email            0
dtype: int64

In [66]:
employees.duplicated().sum()

100

In [68]:
employees["employee_id"].duplicated().sum()

100

In [70]:
employees[pd.to_numeric(employees["age"],errors="coerce")<18]

,employee_id,employee_code,gender,age,department_id,job_title,join_date,salary,email
58,59,EMP00059,Female,-2.0,10.0,Analyst,15/02/2024,6 LPA,NaN
259,260,EMP00260,Female,-2.0,99.0,Intern,NaN,500000,INVALID
302,303,EMP00303,Male,-2.0,6.0,Analyst,NaN,350000,emp303@mail.com
309,310,EMP00310,NaN,-2.0,4.0,Analyst,15/02/2024,350000,INVALID
360,361,EMP00361,male,-2.0,99.0,Engineer,NaN,800000,INVALID
...,...,...,...,...,...,...,...,...,...
9799,9800,EMP09800,F,-2.0,6.0,Engineer,NaN,800000,NaN
9884,9885,EMP09885,male,-2.0,8.0,Manager,15/02/2024,6 LPA,NaN
9977,9978,EMP09978,Male,-2.0,15.0,HR,2025-07-01,800000,NaN
10046,3728,EMP03728,NaN,-2.0,19.0,Engineer,2023-01-15,500000,INVALID
10058,807,EMP00807,male,-2.0,8.0,Engineer,2025-07-01,6 LPA,NaN

In [71]:
employees["gender"].value_counts(dropna=False)

gender
Male      1722
male      1704
NaN       1703
Female    1684
F         1661
M         1626
Name: count, dtype: int64

In [72]:
employees["join_date"].value_counts(dropna=False).head(20)

join_date
NaN           3965
2023-01-15    2097
2025-07-01    2029
15/02/2024    2009
Name: count, dtype: int64

In [73]:
employees["salary"].value_counts(dropna=False).head(20)

salary
-10000    1764
800000    1686
350000    1673
6 LPA     1664
500000    1657
NaN       1656
Name: count, dtype: int64

In [82]:
clean_employees=employees.copy()

In [90]:
clean_employees.columns = (
    clean_employees.columns
    .str.replace('___', '_')
    .str.strip('_')
    .str.lower()
)

In [91]:
clean_employees.columns

Index(['employee__id', 'employee__code', 'gender', 'age', 'department__id',
       'job__title', 'join__date', 'salary', 'email'],
      dtype='object')

In [95]:
clean_employees=clean_employees.replace(r'^\s*$',np.nan,regex=True)

In [100]:
clean_employees.isna().sum()

employee__id         0
employee__code       0
gender            1703
age                244
department__id     434
job__title           0
join__date        3965
salary            1656
email             5007
dtype: int64

In [101]:
clean_employees=clean_employees.drop_duplicates()

In [102]:
clean_employees.duplicated().sum()

0

In [103]:
clean_employees["gender"]=(
    clean_employees["gender"]
    .astype("string")
    .str.strip()
    .str.lower()
)

In [109]:
clean_employees["gender"]=clean_employees["gender"].replace({
    "m":"Male",
    "male":"Male",
    "f":"Female",
    "female":"Female"
})

In [110]:
clean_employees["gender"].value_counts(dropna=False)

gender
Male      5001
Female    3304
<NA>      1695
Name: count, dtype: Int64

In [111]:
clean_employees["gender"].value_counts(dropna=False)

gender
Male      5001
Female    3304
<NA>      1695
Name: count, dtype: Int64

In [112]:
clean_employees["age"]=pd.to_numeric(
    clean_employees["age"],
    errors="coerce"
)

In [114]:
import numpy as np

In [117]:
clean_employees.loc[
(clean_employees["age"]<18)|(clean_employees["age"]>18),"age"]=np.nanclean_employees.loc[
(clean_employees["age"]<18)|(clean_employees["age"]>18),"age"]=np.nan

In [122]:
clean_employees["department__id"] = pd.to_numeric(
    clean_employees["department__id"],
    errors="coerce"
)

In [123]:
clean_employees["join__date"]=pd.to_datetime(
    clean_employees["join__date"],
    errors="coerce",
    dayfirst=True
)

/tmp/ipykernel_98481/4144105081.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  clean_employees["join__date"]=pd.to_datetime(

In [124]:
clean_employees["join__date"].isna().sum()

5917

In [125]:
clean_employees["salary"] = clean_employees["salary"].astype("string")

In [134]:
clean_employees["salary"] = (
    clean_employees["salary"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.strip()
)

AttributeError: Can only use .str accessor with string values!

In [136]:

numeric_series = pd.to_numeric(cleaned_text, errors="coerce")


lpa_mask = clean_employees["salary"].str.contains("LPA", case=False, na=False)


numeric_series[lpa_mask] = numeric_series[lpa_mask] * 100000


clean_employees["salary"] = numeric_series


print(clean_employees["salary"].dtype)

AttributeError: Can only use .str accessor with string values!

In [137]:
print(clean_employees["salary"].head())
print("Data Type:", clean_employees["salary"].dtype)

0    350000
1    350000
2    -10000
3    350000
4    800000
Name: salary, dtype: Int64
Data Type: Int64

In [138]:
clean_employees.loc[clean_employees["salary"]<0 , "salary"]=np.nan

In [140]:
clean_employees["email"]=(
    clean_employees["email"]
    .astype("string")
    .str.strip()
    .str.lower()
)

In [147]:
email_pattern=r"^[^@\s]+@[^@\s]+\.[^@\s]+$"

In [152]:
invalid_email = ~(clean_employees["email"].str.match(
    email_pattern,
    na=False
))

In [154]:
clean_employees.loc[invalid_email,"email"]=np.nan

In [155]:
clean_employees["age"].isna().sum()

10000

In [163]:
age_median=clean_employees["age"].median()
print(age_median)

40.0

In [164]:
clean_employees["age"]=clean_employees["age"].fillna(age_median)

In [165]:
clean_employees["age"].isna().sum()

0

In [161]:
clean_employees["age"] = employees["age"]

In [162]:
clean_employees.loc[
(clean_employees["age"]<18)|(clean_employees["age"]>65),"age"]=np.nan

In [169]:
clean_employees["salary"] = (
    clean_employees
    .groupby("department__id")["salary"]
    .transform(lambda x: x.fillna(x.median()))
)

overall_salary_median = clean_employees["salary"].median()
clean_employees["salary"] = clean_employees["salary"].fillna(overall_salary_median)

In [170]:
print("Remaining NaN values in salary:", clean_employees["salary"].isna().sum())

Remaining NaN values in salary: 0

In [174]:
clean_employees["gender"]=clean_employees["gender"].fillna("Unknow")

In [175]:
clean_employees["gender"].value_counts()

gender
Male      5001
Female    3304
Unknow    1695
Name: count, dtype: Int64

In [177]:
clean_employees["email"].isna().sum()

7523

In [178]:
clean_employees.isna().sum()

employee__id         0
employee__code       0
gender               0
age                  0
department__id     430
job__title           0
join__date        5917
salary               0
email             7523
dtype: int64

In [179]:
clean_employees.duplicated().sum()

0

In [180]:
clean_employees["age"].describe()

count    10000.00000
mean        39.98050
std         11.39453
min         20.00000
25%         31.00000
50%         40.00000
75%         49.00000
max         60.00000
Name: age, dtype: float64

In [181]:
clean_employees["salary"].describe()

count          10000.0
mean          564215.0
std      133618.745586
min           350000.0
25%           500000.0
50%           600000.0
75%           600000.0
max           800000.0
Name: salary, dtype: Float64

In [182]:
clean_employees["gender"].value_counts(dropna=False)

gender
Male      5001
Female    3304
Unknow    1695
Name: count, dtype: Int64

In [183]:
departments=pd.read_csv("departments.csv")

In [184]:
departments.head()

   department_id department_name   location
0              1    Department_1     Mumbai
1              2    Department_2  Hyderabad
2              3    Department_3       Pune
3              4    Department_4       Pune
4              5    Department_5     Mumbai

In [189]:
valid_department_ids = departments["department_id"]

invalid_departments=clean_employees[
~clean_employees["department__id"].isin(valid_department_ids)]

invalid_departments

,employee__id,employee__code,gender,age,department__id,job__title,join__date,salary,email
12,13,EMP00013,Female,22.0,NaN,Analyst,NaT,600000,<NA>
15,16,EMP00016,Unknow,56.0,NaN,Manager,2025-07-01,600000,<NA>
21,22,EMP00022,Female,34.0,NaN,Engineer,2023-01-15,600000,<NA>
25,26,EMP00026,Male,50.0,99.0,Manager,2023-01-15,500000,emp26@mail.com
33,34,EMP00034,Male,39.0,99.0,Analyst,2025-07-01,500000,<NA>
...,...,...,...,...,...,...,...,...,...
9983,9984,EMP09984,Male,20.0,99.0,HR,NaT,500000,emp9984@mail.com
9987,9988,EMP09988,Female,42.0,NaN,Analyst,2023-01-15,600000,<NA>
9989,9990,EMP09990,Male,24.0,99.0,Engineer,2023-01-15,500000,<NA>
9992,9993,EMP09993,Male,58.0,NaN,Intern,NaT,600000,<NA>
9996,9997,EMP09997,Unknow,38.0,99.0,Manager,NaT,500000,emp9997@mail.com

In [190]:
invalid_departments

,employee__id,employee__code,gender,age,department__id,job__title,join__date,salary,email
12,13,EMP00013,Female,22.0,NaN,Analyst,NaT,600000,<NA>
15,16,EMP00016,Unknow,56.0,NaN,Manager,2025-07-01,600000,<NA>
21,22,EMP00022,Female,34.0,NaN,Engineer,2023-01-15,600000,<NA>
25,26,EMP00026,Male,50.0,99.0,Manager,2023-01-15,500000,emp26@mail.com
33,34,EMP00034,Male,39.0,99.0,Analyst,2025-07-01,500000,<NA>
...,...,...,...,...,...,...,...,...,...
9983,9984,EMP09984,Male,20.0,99.0,HR,NaT,500000,emp9984@mail.com
9987,9988,EMP09988,Female,42.0,NaN,Analyst,2023-01-15,600000,<NA>
9989,9990,EMP09990,Male,24.0,99.0,Engineer,2023-01-15,500000,<NA>
9992,9993,EMP09993,Male,58.0,NaN,Intern,NaT,600000,<NA>
9996,9997,EMP09997,Unknow,38.0,99.0,Manager,NaT,500000,emp9997@mail.com

In [191]:
clean_employees.to_csv("employees-cleaned.csv",index=False)